encoding: utf-8

# SEO相关信息
title: lr.cool
description: 酷酷滴LR
keywords: lr,lr.cool
author: lr
footerText: 'Copyright © 2020 <a href="http://beian.miit.gov.cn">粤ICP备2020108670号-1</a>'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'cli.bat', 'dist.tar.gz']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'http://lr.cool'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/products/292965

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# 点击页面撒球特效,不需要请设置为false
extClickspreadEffect: true

# 背景线条特效,不需要请设置为false
extBackgroundEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: 海森堡测不准面包
    url: https://nkiiiiid.github.io
  - title: Mind Hacks
    url: http://mindhacks.cn
  - title: 知青
    url: https://vince-lau.github.io
  - title: TMaize Blog
    url: https://blog.tmaize.net

